### ISSUE TITLE
Did something happen to the servers?

### ISSUE THREAD

**Issue by MittensDoesThings** [CatmanFan/FriishProduce#56] opened 2024-12-18 19:21 UTC
![image](https://github.com/user-attachments/assets/de9856db-04f6-40b1-b4da-46a927317a59)
So when I was trying to inject a Sega Genesis rom, It wouldn't let me export the .WAD It says: "Failed to connect to the Internet." which is strange because I am connected to Internet, then it says: "The remote server returned to an error: 404 Not Found. So I want to assume something happened to the servers. I did try injecting another rom and the same issue applies.

**Comment by saulfabregwiivc** [comment] 2024-12-20 14:06
According to @CatmanFan, the Libretro database have their servers currently down. Not a bug on FriishProduce itself, but a server problem in Libretro database.

Closing as invalid.

**Closed** 2024-12-20 23:45 UTC
Labels: good first issue, question

**Comment by TheLostMeme** [comment] 2025-01-12 01:15
Apologies for reupping this issue, but I am now having the same issue for some reason.
